require.config({
  baseUrl:"/",
  paths:{
    "jquery":"libs/jquery-1.11.3.min",
    "base":"module/base",
    "slider":"module/slider",
    "url":"module/url",
    "template":"libs/template-web",
    "getNewPro":"module/getNewPro",
    "getHotPro":"module/getHotPro",
  },
  shim:{
    base:{
      deps:["jquery"]
    },
    slider:{
      deps:["jquery"]
    },
    getNewPro:{
      deps:["jquery"]
    },
    getHotPro:{
      deps:["jquery"]
    }
  }
})