require(['config'],function(){
    require(['jquery','base',"slider","getNewPro","getHotPro"],function($,base,slider,getNewPro,getHotPro){
      $(function(){
        base.head();
        base.foot();
        slider.slider($("#banner"));
        getNewPro.getData();
        getHotPro.getData();
      });
    });
});
