require(['config'],function(){
    require(['jquery','base',"slider"],function($,base,slider){
      $(function(){
        base.head($("#header"));
        base.foot($("#footer"));
        slider.slider($("#banner"));
      });
    });
});
