require(['config'],function(){
    require(['jquery','base',"slider","getNewPro","getHotPro","getTimePro"],function($,base,slider,getNewPro,getHotPro,getTimePro){
      $(function(){
        //头部
        base.head();
        //尾部
        base.foot();
        //轮播图
        slider.slider($("#banner"));
        //新品首发
        getNewPro.getData();
        getNewPro.change();

        //热门推荐
        getHotPro.getData("bjtj","bjz");
        getHotPro.change();
        //限时抢购
        getTimePro.getData();
      });
    });
});
